"""add audit fields and soft delete

Revision ID: 001_add_audit_fields
Revises:
Create Date: 2024-01-14

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_audit_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 为 users 表添加审计字段
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='修改时间'))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('users', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 tracks 表添加审计字段（已有 created_at, updated_at，只需添加额外的）
    op.add_column('tracks', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('tracks', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('tracks', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 track_points 表添加审计字段
    op.add_column('track_points', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'))
    op.add_column('track_points', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='修改时间'))
    op.add_column('track_points', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('track_points', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('track_points', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 configs 表添加审计字段（已有 updated_at，只需添加额外的）
    op.add_column('configs', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'))
    op.add_column('configs', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('configs', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('configs', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 invite_codes 表添加审计字段（已有 created_at，只需添加额外的）
    op.add_column('invite_codes', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='修改时间'))
    op.add_column('invite_codes', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('invite_codes', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('invite_codes', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 tasks 表添加审计字段（已有 created_at, updated_at，只需添加额外的）
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('tasks', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 为 road_sign_cache 表添加审计字段
    op.add_column('road_sign_cache', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'))
    op.add_column('road_sign_cache', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'), comment='修改时间'))
    op.add_column('road_sign_cache', sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'))
    op.add_column('road_sign_cache', sa.Column('updated_by', sa.Integer(), nullable=True, comment='修改者ID'))
    op.add_column('road_sign_cache', sa.Column('is_valid', sa.Boolean(), nullable=False, server_default='1', comment='是否有效'))

    # 创建索引
    op.create_index('ix_users_is_valid', 'users', ['is_valid'])
    op.create_index('ix_users_created_by', 'users', ['created_by'])
    op.create_index('ix_users_updated_by', 'users', ['updated_by'])

    op.create_index('ix_tracks_is_valid', 'tracks', ['is_valid'])
    op.create_index('ix_tracks_created_by', 'tracks', ['created_by'])
    op.create_index('ix_tracks_updated_by', 'tracks', ['updated_by'])

    op.create_index('ix_track_points_is_valid', 'track_points', ['is_valid'])
    op.create_index('ix_track_points_created_by', 'track_points', ['created_by'])
    op.create_index('ix_track_points_updated_by', 'track_points', ['updated_by'])

    op.create_index('ix_configs_is_valid', 'configs', ['is_valid'])
    op.create_index('ix_configs_created_by', 'configs', ['created_by'])
    op.create_index('ix_configs_updated_by', 'configs', ['updated_by'])

    op.create_index('ix_invite_codes_is_valid', 'invite_codes', ['is_valid'])
    op.create_index('ix_invite_codes_created_by', 'invite_codes', ['created_by'])
    op.create_index('ix_invite_codes_updated_by', 'invite_codes', ['updated_by'])

    op.create_index('ix_tasks_is_valid', 'tasks', ['is_valid'])
    op.create_index('ix_tasks_created_by', 'tasks', ['created_by'])
    op.create_index('ix_tasks_updated_by', 'tasks', ['updated_by'])

    op.create_index('ix_road_sign_cache_is_valid', 'road_sign_cache', ['is_valid'])
    op.create_index('ix_road_sign_cache_created_by', 'road_sign_cache', ['created_by'])
    op.create_index('ix_road_sign_cache_updated_by', 'road_sign_cache', ['updated_by'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 删除索引
    op.drop_index('ix_road_sign_cache_updated_by', 'road_sign_cache')
    op.drop_index('ix_road_sign_cache_created_by', 'road_sign_cache')
    op.drop_index('ix_road_sign_cache_is_valid', 'road_sign_cache')

    op.drop_index('ix_tasks_updated_by', 'tasks')
    op.drop_index('ix_tasks_created_by', 'tasks')
    op.drop_index('ix_tasks_is_valid', 'tasks')

    op.drop_index('ix_invite_codes_updated_by', 'invite_codes')
    op.drop_index('ix_invite_codes_created_by', 'invite_codes')
    op.drop_index('ix_invite_codes_is_valid', 'invite_codes')

    op.drop_index('ix_configs_updated_by', 'configs')
    op.drop_index('ix_configs_created_by', 'configs')
    op.drop_index('ix_configs_is_valid', 'configs')

    op.drop_index('ix_track_points_updated_by', 'track_points')
    op.drop_index('ix_track_points_created_by', 'track_points')
    op.drop_index('ix_track_points_is_valid', 'track_points')

    op.drop_index('ix_tracks_updated_by', 'tracks')
    op.drop_index('ix_tracks_created_by', 'tracks')
    op.drop_index('ix_tracks_is_valid', 'tracks')

    op.drop_index('ix_users_updated_by', 'users')
    op.drop_index('ix_users_created_by', 'users')
    op.drop_index('ix_users_is_valid', 'users')

    # 删除列
    op.drop_column('road_sign_cache', 'is_valid')
    op.drop_column('road_sign_cache', 'updated_by')
    op.drop_column('road_sign_cache', 'created_by')
    op.drop_column('road_sign_cache', 'updated_at')
    op.drop_column('road_sign_cache', 'created_at')

    op.drop_column('tasks', 'is_valid')
    op.drop_column('tasks', 'updated_by')
    op.drop_column('tasks', 'created_by')

    op.drop_column('invite_codes', 'is_valid')
    op.drop_column('invite_codes', 'updated_by')
    op.drop_column('invite_codes', 'created_by')
    op.drop_column('invite_codes', 'updated_at')

    op.drop_column('configs', 'is_valid')
    op.drop_column('configs', 'updated_by')
    op.drop_column('configs', 'created_by')
    op.drop_column('configs', 'created_at')

    op.drop_column('track_points', 'is_valid')
    op.drop_column('track_points', 'updated_by')
    op.drop_column('track_points', 'created_by')
    op.drop_column('track_points', 'updated_at')
    op.drop_column('track_points', 'created_at')

    op.drop_column('tracks', 'is_valid')
    op.drop_column('tracks', 'updated_by')
    op.drop_column('tracks', 'created_by')

    op.drop_column('users', 'is_valid')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')

    # ### end Alembic commands ###
