"""add bearing column to track_points

Revision ID: 002_add_bearing
Revises: 001_add_audit_fields
Create Date: 2025-01-23

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_bearing'
down_revision = '001_add_audit_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_points', sa.Column('bearing', sa.Float(), nullable=True, comment='方位角（度），范围 [0, 360)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_points', 'bearing')
    # ### end Alembic commands ###
