"""add memo to track_points

Revision ID: 003_add_memo
Revises: 002_add_bearing_to_track_points
Create Date: 2025-01-24

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_add_memo'
down_revision = '002_add_bearing_to_track_points'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_points', sa.Column('memo', sa.Text(), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_points', 'memo')
    # ### end Alembic commands ###
