/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AMap: typeof import('./components/map/AMap.vue')['default']
    AnchorSelector: typeof import('./components/overlay-editor/AnchorSelector.vue')['default']
    BMap: typeof import('./components/map/BMap.vue')['default']
    CodeMirrorYamlEditor: typeof import('./components/CodeMirrorYamlEditor.vue')['default']
    DataSourceSelector: typeof import('./components/overlay-editor/DataSourceSelector.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElevationChart: typeof import('./components/charts/ElevationChart.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FontSelector: typeof import('./components/overlay-editor/FontSelector.vue')['default']
    GeoChartPanel: typeof import('./components/geo-editor/GeoChartPanel.vue')['default']
    InterpolationDialog: typeof import('./components/interpolation/InterpolationDialog.vue')['default']
    LeafletMap: typeof import('./components/map/LeafletMap.vue')['default']
    LiveRecordingDialog: typeof import('./components/LiveRecordingDialog.vue')['default']
    NProgress: typeof import('./components/NProgress.vue')['default']
    PenToolMap: typeof import('./components/interpolation/PenToolMap.vue')['default']
    PosterExportDialog: typeof import('./components/PosterExportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./components/ShareDialog.vue')['default']
    TencentMap: typeof import('./components/map/TencentMap.vue')['default']
    TimelineScale: typeof import('./components/geo-editor/TimelineScale.vue')['default']
    TimelineTracks: typeof import('./components/geo-editor/TimelineTracks.vue')['default']
    UniversalMap: typeof import('./components/map/UniversalMap.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
